const hiragana = 'あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをんがぎぐげござじずぜぞだぢづでどばびぶべぼぱぴぷぺぽゔぁぃぅぇぉっゃゅょ'

const n5kanji = '日一国人年大十二本中長出三時行見月分後前生五間上東四今金九入学高円子外八六下来気小七山話女北午百書先名川千水半男西電校語土木聞食車何南万毎白天母火右読友左休父雨'

const n4kanji = '会同事自社発者地業方新場員立開手力問代明動京目通言理体田主題意不作用度強公持野以思家世多正安院心界教文元重近考画海売知道集別物使品計死特私始朝運終台広住無真有口少町料工建空急止送切転研足究楽起着店病質待試族銀早映親験英医仕去味写字答夜音注帰古歌買悪図週室歩風紙黒花春赤青館屋色走秋夏習駅洋旅服夕借曜飲肉貸堂鳥飯勉冬昼茶弟牛魚兄犬妹姉漢'

const five = [
	['上げる'			,'あげる'			,'to raise; to elevate'],
	['雨'			,'あめ'			,'rain'],
	['上'			,'うえ'			,'above, up'],
	['後'			,'あと'			,'behind; after;'],
	['父'			,'ちち'			,'father'],
	['小さい'			,'ちいさい'		,'small; little; tiny'],
	['大学'			,'だいがく'		,'university; college'],
	['出す'			,'だす'			,'to take out; to get out'],
	['出かける'		,'でかける'		,'to leave; to depart'],
	['電気'			,'でんき'			,'electricity'],
	['電車'			,'でんしゃ'		,'train; electric train'],
	['電話'			,'でんわ'			,'phone call'],
	['出る'			,'でる'			,'to leave; to exit'],
	['二人'			,'ふたり'			,'two people; pair; couple'],
	['二つ'			,'ふたつ'			,'two; 2'],
	['二日'			,'ふつか'			,'the second day of the month / 2 days'],
	['外国'			,'がいこく'		,'foreign country'],
	['外国人'		,'がいこくじん'		,'foreigner'],
	['学校'			,'がっこう'		,'school'],
	['学生'			,'がくせい'		,'student'],
	['五'			,'ご'			,'five; 5'],
	['午前'			,'ごぜん'			,'morning; a.m.'],
	['八'			,'はち'			,'eight; 8'],
	['母'			,'はは'			,'mother'],
	['入る'			,'はいる'			,'to enter; to go into'],
	['半'			,'はん'			,'half; semi-; half-past'],
	['花'			,'はな'			,'flower'],
	['話'			,'はなし'			,'talk; speech; chat; conversation'],
	['話す'			,'はなす'			,'to speak; to talk; to converse'],
	['半分'			,'はんぶん'		,'half'],
	['二十日'		,'はつか'			,'twentieth day of the month / 20 days'],
	['左'			,'ひだり'			,'left; left hand side'],
	['東'			,'ひがし'			,'east'],
	['人'			,'ひと'			,'person; human'],
	['一人'			,'ひとり'			,'one person; alone; single'],
	['一つ'			,'ひとつ'			,'one thing; only'],
	['本'			,'ほん'			,'book; volume; script'],
	['百'			,'ひゃく'			,'hundred; 100'],
	['一'			,'いち'			,'one; best; first'],
	['一日'			,'いちにち'		,'one day; all day'],
	['行く'			,'いく'			,'to go; to move'],
	['今'			,'いま'			,'now; the present time; soon'],
	['入れる'			,'いれる'			,'to put in; to insert'],
	['五日'			,'いつか'			,'the fifth day of the month / 5 days'],
	['五つ'			,'いつつ'			,'five; 5'],
	['十'			,'じゅう'			,'ten; 10'],
	['書く'			,'かく'			,'to write; to draw'],
	['買う'			,'かう'			,'to buy; to purchase'],
	['川'			,'かわ'			,'river; stream'],
	['木'			,'き'			,'tree; wood'],
	['聞く'			,'きく'			,'to hear; to listen; to ask'],
	['北'			,'きた'			,'north'],
	['九日'			,'ここのか'		,'ninth day of the month / 9 days'],
	['九つ'			,'ここのつ'		,'nine; 9'],
	['今月'			,'こんげつ'		,'this month'],
	['今年'			,'ことし'			,'this year'],
	['下さい'			,'ください'		,'please'],
	['国'			,'くに'			,'country'],
	['来る'			,'くる'			,'to come'],
	['車'			,'くるま'			,'car; automobile; vehicle'],
	['今日'			,'きょう'			,'today; this day'],
	['九'			,'きゅう'			,'nine; 9'],
	['前'			,'まえ'			,'previous; before; in front; ago'],
	['毎日'			,'まいにち'		,'every day'],
	['毎年'			,'まいとし'		,'every year; yearly; annually'],
	['毎月'			,'まいつき'		,'every month; monthly'],
	['万'			,'まん'			,'ten thousand; 10,000'],
	['右'			,'みぎ'			,'right; right hand side'],
	['三日'			,'みっか'			,'the third day of the month / 3 days'],
	['南'			,'みなみ'			,'south'],
	['見る'			,'みる'			,'to see; to look; to watch'],
	['見せる'			,'みせる'			,'to show; to display'],
	['三つ'			,'みっつ'			,'three; 3'],
	['水'			,'みず'			,'water; fluid; liquid'],
	['六日'			,'むいか'			,'sixth day of the month / 6 days'],
	['六つ'			,'むっつ'			,'six; 6'],
	['長い'			,'ながい'			,'long'],
	['中'			,'なか'			,'inside; in; center'],
	['名前'			,'なまえ'			,'name'],
	['七つ'			,'ななつ'			,'seven; 7'],
	['何'			,'なに'			,'what'],
	['七日'			,'なのか'			,'seventh day of the month / 7 days'],
	['二'			,'に'			,'two; 2'],
	['西'			,'にし'			,'west'],
	['お母さん'		,'おかあさん'		,'mother'],
	['お金'			,'おかね'			,'money'],
	['女'			,'おんな'			,'woman; female'],
	['女の子'		,'おんなのこ'		,'girl'],
	['大きい'			,'おおきい'		,'big; large; great'],
	['大きな'			,'おおきな'		,'big; large; great'],
	['男'			,'おとこ'			,'man; male'],
	['男の子'		,'おとこのこ'		,'boy'],
	['大人'			,'おとな'			,'adult'],
	['お父さん'		,'おとうさん'		,'father'],
	['来月'			,'らいげつ'		,'next month'],
	['来年'			,'らいねん'		,'next year'],
	['六'			,'ろく'			,'six; 6'],
	['先'			,'さき'			,'previous; first; earlier'],
	['三'			,'さん'			,'three; 3'],
	['千'			,'せん'			,'thousand; 1,000'],
	['先月'			,'せんげつ'		,'last month'],
	['先生'			,'せんせい'		,'teacher; instructor; master'],
	['四'			,'し'			,'four; 4'],
	['七'			,'しち'			,'seven; 7'],
	['白'			,'しろ'			,'white'],
	['下'			,'した'			,'below; down; under; bottom'],
	['外'			,'そと'			,'outside'],
	['食べる'			,'たべる'			,'to eat'],
	['高い'			,'たかい'			,'high; tall; expensive'],
	['天気'			,'てんき'			,'weather'],
	['時'			,'とき'			,'time'],
	['時々'			,'ときどき'		,'sometimes'],
	['十日'			,'とおか'			,'tenth day of the month / 10 days'],
	['年'			,'とし'			,'year; age'],
	['上'			,'うえ'			,'above; up; top'],
	['生まれる'		,'うまれる'		,'to be born'],
	['後ろ'			,'うしろ'			,'back; behind'],
	['分かる'			,'わかる'			,'to understand'],
	['山'			,'やま'			,'mountain'],
	['休み'			,'やすみ'			,'rest; vacation; holiday'],
	['休む'			,'やすむ'			,'to rest'],
	['八つ'			,'やっつ'			,'eight: 8'],
	['四日'			,'よっか'			,'fourth day of the month / 4 days'],
	['読む'			,'よむ'			,'to read'],
	['四つ'			,'よっつ'			,'four; 4'],
	['八日'			,'ようか'			,'eighth day of the month / 8 days'],
]

const four = [
	['上がる'			,'あがる'			,'to rise'],
	['味'			,'あじ'			,'flavor; taste'],
	['赤ちゃん'		,'あかちゃん'		,'baby; infant'],
	['安心'			,'あんしん'		,'peace of mind'],
	['集まる'			,'あつまる'		,'to gather; to collect'],
	['集める'			,'あつめる'		,'to gather; to collect'],
	['僕'			,'ぼく'			,'I'],
	['力'			,'ちから'			,'force; strength; power'],
	['地理'			,'ちり'			,'geography'],
	['中学校'		,'ちゅうがっこう'		,'junior high school; middle school'],
	['注意'			,'ちゅうい'		,'caution'],
	['大分'			,'だいぶ'			,'considerably; greatly; a lot'],
	['大学生'		,'だいがくせい'		,'university student; college student'],
	['大事'			,'だいじ'			,'important; serious; crucial'],
	['大体'			,'だいたい'		,'roughly'],  
	['ご主人'			,'ごしゅじん'		,'your husband; her husband'],
	['運ぶ'			,'はこぶ'			,'to carry'],
	['花見'			,'はなみ'			,'cherry blossom viewing; flower viewing'],
	['発音'			,'はつおん'		,'pronunciation'],
	['火'			,'ひ'			,'fire'],
	['開く'			,'ひらく'			,'to open; to undo; to unseal; to unpack'],
	['昼間'			,'ひるま'			,'daytime; during the day'],
	['昼休み'		,'ひるやすみ'		,'lunch break; noon rest period'],
	['一度'			,'いちど'			,'once; one time'],
	['以外'			,'いがい'			,'with the exception of; excepting'],
	['医学'			,'いがく'			,'medical science; medicine'],
	['以上'			,'いじょう'		,'...and more; ...and upwards'],
	['以下'			,'いか'			,'not exceeding'],
	['意見'			,'いけん'			,'opinion; view; comment'],
	['生き物'		,'いきもの'		,'living thing'],
	['生きる'			,'いきる'			,'to live'],
	['色んな'			,'いろんな'		,'various'],
	['急ぐ'			,'いそぐ'			,'to hurry; to rush; to hasten'],
	['字'			,'じ'			,'character'],
	['時代'			,'じだい'			,'period'],
	['人口'			,'じんこう'		,'population'],
	['人生'			,'じんせい'		,'human life'],
	['十分'			,'じゅうぶん'		,'enough; sufficient; plenty'],
	['帰り'			,'かえり'			,'return; coming back'],
	['会場'			,'かいじょう'		,'assembly hall; meeting place'],
	['会話'			,'かいわ'			,'conversation'],
	['火事'			,'かじ'			,'fire'],
	['考える'			,'かんがえる'		,'to think'], 
	['代わり'			,'かわり'			,'instead; in place'],
	['変わる'			,'かわる'			,'to change'],
	['通う'			,'かよう'			,'to commute'],
	['計画'			,'けいかく'		,'to plan'],
	['見物'			,'けんぶつ'		,'sightseeing; visit'],
	['研究'			,'けんきゅう'		,'research'],
	['研究室'		,'けんきゅうしつ'	,'laboratory'],
	['気'			,'き'			,'spirit'],
	['気分'			,'きぶん'			,'feeling; mood'],
	['聞こえる'		,'きこえる'		,'to be heard; to be said'],
	['気持ち'			,'きもち'			,'feeling'],
	['着物'			,'きもの'			,'kimono'],
	['子'			,'こ'			,'child'],
	['心'			,'こころ'			,'heart'],
	['今度'			,'こんど'			,'this time; next time'],
	['この間'			,'このあいだ'		,'the other day; recently'],
	['今夜'			,'こんや'			,'this evening; tonight'],
	['答え'			,'こたえ'			,'response'],
	['小鳥'			,'ことり'			,'small bird'],
	['校長'			,'こうちょう'		,'principal; headmaster'],
	['工業'			,'こうぎょう'		,'industry'],
	['工場'			,'こうじょう'		,'factory'],
	['高校'			,'こうこう'			,'senior high school; high school'],
	['高校生'		,'こうこうせい'		,'hight school student'],
	['下さる'			,'くださる'		,'(respectful) to give'],
	['空気'			,'くうき'			,'air'],
	['教会'			,'きょうかい'		,'church'],
	['急'			,'きゅう'			,'sudden; unexpected'],
	['急行'			,'きゅうこう'		,'hurrying; rushing'],
	['真ん中'		,'まんなか'		,'middle; centre; center'],
	['見える'			,'みえる'			,'to be seen; to be in sight'],
	['見つかる'		,'みつかる'		,'to discover; to find'],
	['生'			,'なま'			,'raw'],
	['入学'			,'にゅうがく'		,'enrollment'],
	['入院'			,'にゅういん'		,'hospitalization'],
	['お出でになる'	,'おいでになる'		,'(respectful) to be'],
	['行う'			,'おこなう'		,'to perform; to do; to carry out'],
	['起こす'			,'おこす'			,'to wake'],
	['屋上'			,'おくじょう'		,'rooftop'],
	['送る'			,'おくる'			,'to send'],
	['思い出す'		,'おもいだす'		,'to remember'],
	['下りる'			,'おりる'			,'to get off'],
	['音'			,'おと'			,'sound; note'],
	['終わり'			,'おわり'			,'the end'],
	['親'			,'おや'			,'parents'],
	['旅館'			,'りょかん'		,'traditional inn'],
	['下がる'			,'さがる'			,'to get down'],
	['下げる'			,'さげる'			,'to lower'],
	['生物'			,'せいぶつ'		,'living thing'],
	['西洋'			,'せいよう'		,'the west; Western countries'],
	['世界'			,'せかい'			,'the world'],
	['社長'			,'しゃちょう'		,'company president; director'],
	['社会'			,'しゃかい'		,'society; community'],
	['仕方'			,'しかた'			,'way; method'],
	['試験'			,'しけん'			,'examination'],
	['品物'			,'しなもの'		,'goods'],
	['新聞社'		,'しんぶんしゃ'		,'newspaper company'],
	['親切'			,'しんせつ'		,'kindness'],
	['知らせる'		,'しらせる'		,'to notify'],
	['下着'			,'したぎ'			,'underwear'],
	['食料品'		,'しょくりょうひん'	,'food; groceries'],
	['小学校'		,'しょうがっこう'		,'elementary school'],
	['生じる'			,'しょうじる'		,'to produce'],
	['水道'			,'すいどう'		,'water supply'],
	['空く'			,'すく'			,'to be hungry'],
	['正しい'			,'ただしい'		,'right; correct'],
	['台風'			,'たいふう'		,'typhoon'],
	['楽しみ'			,'たのしみ'		,'looking forward to; enjoyment'],
	['足りる'			,'たりる'			,'to be sufficient; to be enough'],
	['足す'			,'たす'			,'to add'],
	['建てる'			,'たてる'			,'to build'],
	['店員'			,'てんいん'		,'employee (of a store); clerk'],
	['特急'			,'とっきゅう'		,'limited express'],
	['特別'			,'とくべつ'		,'special; particular'],
	['特に'			,'とくに'			,'particularly; especially'],
	['止める'			,'とめる'			,'to stop something'],
	['月'			,'つき'			,'moon'],
	['動く'			,'うごく'			,'to move'],
	['生まれ'			,'うまれ'			,'birth'],
	['運転手'		,'うんてんしゅ'		,'driver'],
	['売り場'			,'うりば'			,'selling area'],
	['写す'			,'うつす'			,'to duplicate'],
	['別れる'			,'わかれる'		,'to separate'],
	['止む'			,'やむ'			,'to stop'],
	['用'			,'よう'			,'business; task; errand; use'],
	['用意'			,'ようい'			,'preparation; arrangements'],
	['用事'			,'ようじ'			,'tasks; errand'],

	['下手'			,'へた'			,'unskillful; poor; awkward'],
	['上手'			,'じょうず'		,'skillful; skilled; good (at)'],
	['手'			,'て'			,'hand; arm'],
	['立つ'			,'たつ'			,'to stand; to stand up'],
	['手紙'			,'てがみ'			,'letter'],
	['夜'			,'よる'			,'evening; night'],
]

const three = [
	[''				,''				,''],
	[''				,''				,''],
		
	[''				,''				,''],
	[''				,''				,''],
	[''				,''				,''],
]

const two = [
	[''				,''				,''],
	[''				,''				,''],
	
	['浴びる'			,'あびる'			,'to bath; to shower'],
	[''				,''				,''],
	[''				,''				,''],
]

const one = [
	[''				,''				,''],
	[''				,''				,''],

	[''				,''				,''],
	[''				,''				,''],
	[''				,''				,''],
]

const n5vocab = [
	["浴びる",			"to bathe; to shower",																"あびる",				"abiru"],
	["危ない",			"dangerous",																		"あぶない",			"abunai"],
	["上げる",			"to raise; to elevate",																"あげる",				"ageru"],
	["赤",				"red; crimson; scarlet ",															"あか",				"aka"],
	["赤い",				"red; crimson; scarlet ",															"あかい",				"akai"],
	["明るい",			"bright; light",																	"あかるい",			"akarui"],
	["開ける",			"to open (a door, etc.); to unwrap (e.g. parcel, package); to unlock",				"あける",				"akeru"],
	["秋",				"autumn; fall",																		"あき",				"aki"],
	["開く",				"to open (e.g. doors, business, etc)",												"あく",				"aku"],
	["甘い",				"sweet; sweet-tasting; sugary; naive; indulgent",									"あまい",				"amai"],
	["飴",				"candy",																			"あめ",				"ame"],
	["雨",				"rain",																				"あめ",				"ame"],
	["姉",				"older sister; elder sister",														"あね",				"ane"],
	["兄",				"elder brother; older brother",														"あに",				"ani"],
	["青",				"blue; azure",																		"あお",				"ao"],
	["青い",				"blue; azure",																		"あおい",				"aoi"],
	["洗う",				"to wash",																			"あらう",				"arau"],
	["歩く",				"to walk",																			"あるく",				"aruku"],
	["朝",				"morning",																			"あさ",				"asa"],
	["朝ご飯",			"breakfast",																		"あさごはん",			"asagohan"],
	["明後日",			"day after tomorrow",																"あさって",			"asatte"],
	["足",				"foot; leg; paw; arm",																"あし",				"ashi"],
	["明日",				"tomorrow",																			"あした",				"ashita"],
	["遊ぶ",				"to play; to enjoy oneself",														"あそぶ",				"asobu"],
	["頭",				"head",																				"あたま",				"atama"],
	["新しい",			"new; novel; fresh; recent; latest",												"あたらしい",			"atarashii"],
	["暖かい",			"warm",																				"あたたかい",			"atatakai"],
	["後",				"behind; after; remainder; left; also",												"あと",				"ato"],
	["厚い",				"thick",																			"あつい",				"atsui"],
	["暑い",				"hot; sultry",																		"あつい",				"atsui"],
	["熱い",				"hot",																				"あつい",				"atsui"],
	["会う",				"to meet; to encounter; to see",													"あう",				"au"],
	["晩ご飯",			"dinner; evening meal",																"ばんごはん",			"bangohan"],
	["番号",				"number",																			"ばんごう",			"bangou"],
	["勉強",				"to study",																			"べんきょう",			"benkyou"],
	["便利",				"convenient; handy; useful",														"べんり",				"benri"],
	["帽子",				"hat; cap",																			"ぼうし",				"boushi"],
	["文章",				"sentence",																			"ぶんしょう",			"bunshou"],
	["豚肉",				"pork",																				"ぶたにく",			"butaniku"],
	["病院",				"hospital",																			"びょういん",			"byouin"],
	["病気",				"illness; disease; sickness",														"びょうき",			"byouki"],
	["茶色",				"brown",																			"ちゃいろ",			"chairo"],
	["茶碗",				"rice bowl; tea cup; teacup",														"ちゃわん",			"chawan"],
	["父",				"father",																			"ちち",				"chichi"],
	["違う",				"to differ",																		"ちがう",				"chigau"],
	["小さい",			"small; little; tiny",																"ちいさい",			"chiisai"],
	["小さな",			"small; little; tiny",																"ちいさな",			"chiisana"],
	["近い",				"near; close",																		"ちかい",				"chikai"],
	["地下鉄",			"subway; underground train",														"ちかてつ",			"chikatetsu"],
	["地図",				"map",																				"ちず",				"chizu"],
	["丁度",				"exactly",																			"ちょうど",				"choudo"],
	["台所",				"kitchen",																			"だいどころ",			"daidokoro"],
	["大学",				"university; college",																"だいがく",			"daigaku"],
	["大丈夫",			"OK; okay; alright; problem free",													"だいじょうぶ",			"daijoubu"],
	["大好き",			"love; like; like very much",														"だいすき",			"daisuki"],
	["誰",				"who",																				"だれ",				"dare"],
	["誰か",				"someone; somebody",																"だれか",				"dareka"],
	["出す",				"to take out; to get out; to put out; to reveal",									"だす",				"dasu"],
	["出口",				"exit; gateway; way out",															"でぐち",				"deguchi"],
	["出かける",			"to go out; to leave; to depart",													"でかける",			"dekakeru"],
	["電気",				"electricity",																		"でんき",				"denki"],
	["電車",				"train; electric train",															"でんしゃ",			"densha"],
	["電話",				"telephone (call / device); phone call",											"でんわ",				"denwa"],
	["出る",				"to leave; to exit; to appear; to go out",											"でる",				"deru"],
	["動物",				"animal",																			"どうぶつ",			"doubutsu"],
	["土曜日",			"Saturday",																			"どようび",			"doyoubi"],
	["絵",				"picture",																			"え",				"e"],
	["映画",				"movie; film",																		"えいが",				"eiga"],
	["映画館",			"movie theater; cinema",															"えいがかん",			"eigakan"],
	["英語",				"English language",																	"えいご",				"eigo"],
	["駅",				"station",																			"えき",				"eki"],
	["鉛筆",				"pencil",																			"えんぴつ",			"enpitsu"],
	["吹く",				"to blow (of the wind)",															"ふく",				"fuku"],
	["服",				"clothes",																			"ふく",				"fuku"],
	["降る",				"to fall",																			"ふる",				"furu"],
	["古い",				"old (not used for people)",														"ふるい",				"furui"],
	["二人",				"two people; pair; couple",															"ふたり",				"futari"],
	["二つ",				"two; 2",																			"ふたつ",				"futatsu"],
	["太い",				"fat; thick",																		"ふとい",				"futoi"],
	["二日",				"the second day of the month / 2 days",												"ふつか",				"futsuka"],
	["封筒",				"envelope",																			"ふうとう",			"fuutou"],
	["冬",				"winter",																			"ふゆ",				"fuyu"],
	["外国",				"foreign country",																	"がいこく",			"gaikoku"],
	["外国人",			"foreigner; foreign citizen; foreign national; alien; non-Japanese",				"がいこくじん",			"gaikokujin"],
	["学校",				"school",																			"がっこう",			"gakkou"],
	["学生",				"student",																			"がくせい",			"gakusei"],
	["玄関",				"entrance",																			"げんかん",			"genkan"],
	["元気",				"lively; full of spirit; energetic; healthy",										"げんき",				"genki"],
	["月曜日",			"Monday",																			"げつようび",			"getsuyoubi"],
	["銀行",				"bank",																				"ぎんこう",			"ginkou"],
	["五",				"five; 5",																			"ご",				"go"],
	["午後",				"afternoon; p.m.",																	"ごご",				"gogo"],
	["ご飯",				"cooked rice; meal",																"ごはん",				"gohan"],
	["午前",				"morning; a.m.",																	"ごぜん",				"gozen"],
	["牛肉",				"beef",																				"ぎゅうにく",			"gyuuniku"],
	["牛乳",				"(cow's) milk",																		"ぎゅうにゅう",			"gyuunyuu"],
	["歯",				"tooth",																			"は",				"ha"],
	["八",				"eight: 8",																			"はち",				"hachi"],
	["葉書",				"postcard",																			"はがき",				"hagaki"],
	["母",				"mother",																			"はは",				"haha"],
	["入る",				"to enter; to go into",																"はいる",				"hairu"],
	["灰皿",				"ashtray",																			"はいざら",			"haizara"],
	["始まる",			"to begin",																			"はじまる",			"hajimaru"],
	["初めて",			"for the first time",																"はじめて",			"hajimete"],
	["箱",				"box; crate",																		"はこ",				"hako"],
	["履く",				"to wear, to put on trousers",														"はく",				"haku"],
	["半",				"half; semi-; half-past",															"はん",				"han"],
	["花",				"flower",																			"はな",				"hana"],
	["鼻",				"nose",																				"はな",				"hana"],
	["話",				"talk; speech; chat; conversation",													"はなし",				"hanashi"],
	["話す",				"to speak; to talk; to converse",													"はなす",				"hanasu"],
	["半分",				"half",																				"はんぶん",			"hanbun"],
	["晴れ",				"clear weather",																	"はれ",				"hare"],
	["晴れる",			"to be sunny",																		"はれる",				"hareru"],
	["貼る",				"to stick; to paste",																"はる",				"haru"],
	["春",				"spring; springtime",																"はる",				"haru"],
	["箸",				"chopsticks",																		"はし",				"hashi"],
	["橋",				"bridge",																			"はし",				"hashi"],
	["走る",				"to run",																			"はしる",				"hashiru"],
	["二十歳",			"20 years old; twenty years old",													"はたち",				"hatachi"],
	["働く",				"to work",																			"はたらく",			"hataraku"],
	["二十日",			"twentieth day of the month / 20 days",												"はつか",				"hatsuka"],
	["早い",				"fast; early",																		"はやい",				"hayai"],
	["速い",				"fast; quick; hasty; brisk",														"はやい",				"hayai"],
	["辺",				"area",																				"へん",				"hen"],
	["下手",				"unskillful; poor; awkward",														"へた",				"heta"],
	["部屋",				"room",																				"へや",				"heya"],
	["左",				"left; left hand side",																"ひだり",				"hidari"],
	["東",				"east",																				"ひがし",				"higashi"],
	["飛行機",			"airplane; aircraft",																"ひこうき",			"hikouki"],
	["引く",				"to pull",																			"ひく",				"hiku"],
	["弾く",				"to play",																			"ひく",				"hiku"],
	["低い",				"short; low",																		"ひくい",				"hikui"],
	["暇",				"free time",																		"ひま",				"hima"],
	["広い",				"spacious; vast; wide",																"ひろい",				"hiroi"],
	["昼",				"noon; midday; daytime; lunch",														"ひる",				"hiru"],
	["昼ご飯",			"lunch",																			"ひるごはん",			"hirugohan"],
	["人",				"person; human",																	"ひと",				"hito"],
	["一人",				"one person; alone; single",														"ひとり",				"hitori"],
	["一つ",				"one thing; only",																	"ひとつ",				"hitotsu"],
	["本",				"book; volume; script",																"ほん",				"hon"],
	["本棚",				"bookshelf; bookcase",																"ほんだな",			"hondana"],
	["本当",				"truth; reality; actuality; fact",													"ほんとう",			"hontou"],
	["欲しい",			"want",																				"ほしい",				"hoshii"],
	["細い",				"thin; slender",																	"ほそい",				"hosoi"],
	["百",				"100; hundred",																		"ひゃく",				"hyaku"],
	["一",				"one; best; first; foremost; start",												"いち",				"ichi"],
	["一番",				"number one; first; 1st, first place; best; most",									"いちばん",			"ichiban"],
	["一日",				"one day; all day",																	"いちにち",			"ichinichi"],
	["家",				"house; residence; family",															"いえ",				"ie"],
	["池",				"pond",																				"いけ",				"ike"],
	["行く",				"to go; to move",																	"いく",				"iku"],
	["今",				"now; the present time; soon",														"いま",				"ima"],
	["意味",				"meaning; significance; sense",														"いみ",				"imi"],
	["妹",				"younger sister",																	"いもうと",			"imouto"],
	["犬",				"dog",																				"いぬ",				"inu"],
	["入れる",			"to put in; to let in; to take in; to bring in; to insert; to install",				"いれる",				"ireru"],
	["入口",				"entrance; entry; gate",															"いりぐち",			"iriguchi"],
	["色",				"colour; color",																	"いろ",				"iro"],
	["色々",				"various",																			"いろいろ",			"iroiro"],
	["居る",				"to be; to have",																	"いる",				"iru"],
	["要る",				"to be needed",																		"いる",				"iru"],
	["医者",				"(medical) doctor; physician",														"いしゃ",				"isha"],
	["忙しい",			"busy",																				"いそがしい",			"isogashii"],
	["一緒",				"together; at the same time; same; identical",										"いっしょ",				"issho"],
	["椅子",				"chair",																			"いす",				"isu"],
	["痛い",				"painful; sore",																	"いたい",				"itai"],
	["五日",				"the fifth day of the month / 5 days",												"いつか",				"itsuka"],
	["五つ",				"five; 5",																			"いつつ",				"itsutsu"],
	["言う",				"to say; to call",																	"いう",				"iu"],
	["嫌",				"unpleasant",																		"いや",				"iya"],
	["字引",				"dictionary",																		"じびき",				"jibiki"],
	["自分",				"myself; yourself; oneself; himself; herself; i; me",								"じぶん",				"jibun"],
	["自動車",			"automobile; motorcar; motor vehicle; car",											"じどうしゃ",			"jidousha"],
	["時間",				"time; hour(s)",																	"じかん",				"jikan"],
	["辞書",				"dictionary",																		"じしょ",				"jisho"],
	["自転車",			"bicycle",																			"じてんしゃ",			"jitensha"],
	["丈夫",				"strong; durable",																	"じょうぶ",			"joubu"],
	["上手",				"skillful; skilled; proficient; good (at)",											"じょうず",			"jouzu"],
	["授業",				"lesson; class work",																"じゅぎょう",			"jugyou"],
	["十",				"ten; 10",																			"じゅう",				"juu"],
	["花瓶",				"a vase",																			"かびん",				"kabin"],
	["角",				"a corner; angle",																	"かど",				"kado"],
	["帰る",				"to go back",																		"かえる",				"kaeru"],
	["返す",				"to return something",																"かえす",				"kaesu"],
	["鍵",				"key",																				"かぎ",				"kagi"],
	["階段",				"stairs; stairway; staircase",														"かいだん",			"kaidan"],
	["買い物",			"shopping; purchased goods",														"かいもの",			"kaimono"],
	["会社",				"company; corporation",																"かいしゃ",			"kaisha"],
	["掛かる",			"to take (a resource, e.g. time or money)",											"かかる",				"kakaru"],
	["掛ける",			"to hang up; to make (a call);",													"かける",				"kakeru"],
	["書く",				"to write; to compose; to pen; to draw",											"かく",				"kaku"],
	["紙",				"paper",																			"かみ",				"kami"],
	["漢字",				"kanji",																			"かんじ",				"kanji"],
	["体",				"body",																				"からだ",				"karada"],
	["辛い",				"spicy",																			"からい",				"karai"],
	["借りる",			"to borrow",																		"かりる",				"kariru"],
	["軽い",				"light",																			"かるい",				"karui"],
	["傘",				"umbrella",																			"かさ",				"kasa"],
	["貸す",				"to lend; to loan",																	"かす",				"kasu"],
	["方",				"way of doing something",															"かた",				"kata"],
	["家庭",				"household",																		"かてい",				"katei"],
	["買う",				"to buy; to purchase",																"かう",				"kau"],
	["川",				"river; stream",																	"かわ",				"kawa"],
	["可愛い",			"cute",																				"かわいい",			"kawaii"],
	["火曜日",			"Tuesday",																			"かようび",			"kayoubi"],
	["風邪",				"a cold",																			"かぜ",				"kaze"],
	["風",				"wind",																				"かぜ",				"kaze"],
	["家族",				"family; members of a family",														"かぞく",				"kazoku"],
	["警官",				"policeman; police officer",														"けいかん",			"keikan"],
	["結婚",				"marriage",																			"けっこん",			"kekkon"],
	["結構",				"splendid, enough",																	"けっこう",				"kekkou"],
	["今朝",				"this morning",																		"けさ",				"kesa"],
	["消す",				"to erase, to turn off power",														"けす",				"kesu"],
	["木",				"tree; shrub; bush; wood; timber",													"き",				"ki"],
	["消える",			"to disappear",																		"きえる",				"kieru"],
	["黄色い",			"yellow",																			"きいろい",			"kiiroi"],
	["聞く",				"to hear; to listen (to music); to ask; to learn of",								"きく",				"kiku"],
	["昨日",				"yesterday",																		"きのう",				"kinou"],
	["金曜日",			"Friday",																			"きんようび",			"kinyoubi"],
	["切符",				"ticket",																			"きっぷ",				"kippu"],
	["嫌い",				"hate",																				"きらい",				"kirai"],
	["綺麗",				"pretty; lovely; beautiful",														"きれい",				"kirei"],
	["切る",				"to cut",																			"きる",				"kiru"],
	["着る",				"to wear",																			"きる",				"kiru"],
	["喫茶店",			"coffee shop; tearoom; cafe",														"きっさてん",			"kissaten"],
	["北",				"north",																			"きた",				"kita"],
	["汚い",				"dirty",																			"きたない",			"kitanai"],
	["切手",				"stamp (postage)",																	"きって",				"kitte"],
	["子供",				"child",																			"こども",				"kodomo"],
	["声",				"voice",																			"こえ",				"koe"],
	["九日",				"ninth day of the month / 9 days",													"ここのか",			"kokonoka"],
	["九つ",				"nine; 9",																			"ここのつ",			"kokonotsu"],
	["困る",				"to be troubled",																	"こまる",				"komaru"],
	["今晩",				"tonight; this evening",															"こんばん",			"konban"],
	["今月",				"this month",																		"こんげつ",			"kongetsu"],
	["今週",				"this week",																		"こんしゅう",			"konshuu"],
	["答える",			"to answer",																		"こたえる",			"kotaeru"],
	["言葉",				"word; words",																		"ことば",				"kotoba"],
	["今年",				"this year",																		"ことし",				"kotoshi"],
	["交番",				"police box",																		"こうばん",			"kouban"],
	["紅茶",				"black tea",																		"こうちゃ",			"koucha"],
	["公園",				"park",																				"こうえん",			"kouen"],
	["交差点",			"intersection",																		"こうさてん",			"kousaten"],
	["口",				"mouth, opening",																	"くち",				"kuchi"],
	["果物",				"fruit",																			"くだもの",			"kudamono"],
	["下さい",			"please",																			"ください",			"kudasai"],
	["曇り",				"cloudiness; cloudy weather",														"くもり",				"kumori"],
	["曇る",				"to become cloudy; to become dim",													"くもる",				"kumoru"],
	["国",				"country; state; region",															"くに",				"kuni"],
	["暗い",				"dark; gloomy; murky",																"くらい",				"kurai"],
	["黒",				"black",																			"くろ",				"kuro"],
	["黒い",				"black",																			"くろい",				"kuroi"],
	["来る",				"to come",																			"くる",				"kuru"],
	["車",				"car; automobile; vehicle",															"くるま",				"kuruma"],
	["薬",				"medicine",																			"くすり",				"kusuri"],
	["靴",				"shoes",																			"くつ",				"kutsu"],
	["靴下",				"socks",																			"くつした",			"kutsushita"],
	["去年",				"last year",																		"きょねん",			"kyonen"],
	["今日",				"today; this day",																	"きょう",				"kyou"],
	["兄弟",				"siblings; brothers and sisters; mate",												"きょうだい",			"kyoudai"],
	["教室",				"classroom",																		"きょうしつ",			"kyoushitsu"],
	["九",				"nine; 9",																			"きゅう",				"kyuu"],
	["町",				"town; block; neighborhood",														"まち",				"machi"],
	["窓",				"window",																			"まど",				"mado"],
	["前",				"previous; before; in front; ago",													"まえ",				"mae"],
	["曲がる",			"to turn; to bend",																	"まがる",				"magaru"],
	["毎朝",				"every morning",																	"まいあさ",			"maiasa"],
	["毎晩",				"every night",																		"まいばん",			"maiban"],
	["毎日",				"every day",																		"まいにち",			"mainichi"],
	["毎週",				"every week",																		"まいしゅう",			"maishuu"],
	["毎年",				"every year; yearly; annually",														"まいとし",			"まいねん",			"maitoshi",  		"mainen"],
	["毎月",				"every month; monthly",																"まいつき",			"maitsuki"],
	["万",				"10000; ten thousand",																"まん",				"man"],
	["万年筆",			"fountain pen",																		"まんねんひつ",			"mannenhitsu"],
	["丸い",				"round; circular",																	"まるい",				"marui"],
	["真っ直ぐ",			"straight ahead; direct",															"まっすぐ",			"massugu"],
	["待つ",				"to wait",																			"まつ",				"matsu"],
	["不味い",			"unpleasant",																		"まずい",				"mazui"],
	["目",				"eye",																				"め",				"me"],
	["眼鏡",				"glasses",																			"めがね",				"megane"],
	["道",				"road; street",																		"みち",				"michi"],
	["緑",				"green",																			"みどり",				"midori"],
	["磨く",				"to polish; to shine; to brush (e.g. teeth)",										"みがく",				"migaku"],
	["右",				"right; right hand side",															"みぎ",				"migi"],
	["短い",				"short",																			"みじかい",			"mijikai"],
	["三日",				"the third day of the month / 3 days",												"みっか",				"mikka"],
	["耳",				"ear; hearing",																		"みみ",				"mimi"],
	["南",				"south",																			"みなみ",				"minami"],
	["皆さん",			"everyone",																			"みなさん",			"minasan"],
	["見る",				"to see; to look; to watch; to view; to observe",									"みる",				"miru"],
	["店",				"store; shop; establishment; restaurant",											"みせ",				"mise"],
	["見せる",			"to show; to display",																"みせる",				"miseru"],
	["三つ",				"three; 3",																			"みっつ",				"mittsu"],
	["水",				"water; fluid; liquid",																"みず",				"mizu"],
	["木曜日",			"Thursday",																			"もくようび",			"mokuyoubi"],
	["門",				"gate",																				"もん",				"mon"],
	["問題",				"problem; question (e.g. on a test)",												"もんだい",			"mondai"],
	["物",				"thing",																			"もの",				"mono"],
	["持つ",				"to hold",																			"もつ",				"motsu"],
	["もう一度",			"once more; again",																	"もういちど",			"mouichido"],
	["六日",				"sixth day of the month / 6 days",													"むいか",				"muika"],
	["向こう",			"over there",																		"むこう",				"mukou"],
	["村",				"village",																			"むら",				"mura"],
	["六つ",				"six; 6",																			"むっつ",				"muttsu"],
	["難しい",			"difficult",																		"むずかしい",			"muzukashii"],
	["長い",				"long (distance); long (time); lengthy.",											"ながい",				"nagai"],
	["中",				"inside; in; within; center",														"なか",				"naka"],
	["鳴く",				"animal noise. to chirp",															"なく",				"naku"],
	["無くす",			"to lose (something)",																"なくす",				"nakusu"],
	["名前",				"name; full name; given name",														"なまえ",				"namae"],
	["七つ",				"seven; 7",																			"ななつ",				"nanatsu"],
	["何",				"what",																				"なに",				"nani"],
	["七日",				"seventh day of the month / 7 days",												"なのか",				"nanoka"],
	["並べる",			"to line up; to set up",															"ならべる",			"naraberu"],
	["並ぶ",				"to line up; to stand in a line",													"ならぶ",				"narabu"],
	["習う",				"to be taught; to learn (from a teacher)",											"ならう",				"narau"],
	["夏",				"summer",																			"なつ",				"natsu"],
	["夏休み",			"summer vacation; summer holiday",													"なつやすみ",			"natsuyasumi"],
	["何故",				"why; how",																			"なぜ",				"naze"],
	["猫",				"cat",																				"ねこ",				"neko"],
	["寝る",				"to sleep; to go to bed; to lie down",												"ねる",				"neru"],
	["二",				"two; 2",																			"に",				"ni"],
	["日曜日",			"Sunday",																			"にちようび",			"nichiyoubi"],
	["賑やか",			"bustling; busy",																	"にぎやか",			"nigiyaka"],
	["日記",				"diary; journal",																	"にっき",				"nikki"],
	["肉",				"meat",																				"にく",				"niku"],
	["荷物",				"luggage; baggage",																	"にもつ",				"nimotsu"],
	["西",				"west",																				"にし",				"nishi"],
	["庭",				"garden",																			"にわ",				"niwa"],
	["登る",				"to climb",																			"のぼる",				"noboru"],
	["飲み物",			"drink; beverage",																	"のみもの",			"nomimono"],
	["飲む",				"to drink",																			"のむ",				"nomu"],
	["乗る",				"to get on (train, plane, bus, ship, etc.)",										"のる",				"noru"],
	["脱ぐ",				"to take off clothes",																"ぬぐ",				"nugu"],
	["温い",				"luke warm",																		"ぬるい",				"nurui"],
	["伯母さん",			"aunt; old lady",																	"おばさん",			"obasan"],
	["お弁当",			"lunch box; Japanese box lunch",													"おべんとう",			"obentou"],
	["覚える",			"to remember",																		"おぼえる",			"oboeru"],
	["お茶",				"tea",																				"おちゃ",				"ocha"],
	["お風呂",			"bath",																				"おふろ",				"ofuro"],
	["美味しい",			"delicious",																		"おいしい",			"oishii"],
	["伯父さん",			"uncle; old man; mister",															"おじさん",			"ojisan"],
	["お母さん",			"mother; mom; mum; ma",																"おかあさん",			"okaasan"],
	["お金",				"money",																			"おかね",				"okane"],
	["お菓子",			"confections; sweets; candy",														"おかし",				"okashi"],
	["起きる",			"to get up; to wake up",															"おきる",				"okiru"],
	["置く",				"to put; to place",																	"おく",				"oku"],
	["奥さん",			"wife; your wife; his wife",														"おくさん",			"okusan"],
	["お巡りさん",			"police officer (friendly term for policeman)",										"おまわりさん",			"omawari san"],
	["重い",				"heavy",																			"おもい",				"omoi"],
	["面白い",			"interesting",																		"おもしろい",			"omoshiroi"],
	["同じ",				"same",																				"おなじ",				"onaji"],
	["お腹",				"stomach",																			"おなか",				"onaka"],
	["お姉さん",			"elder sister; young lady; miss; ma'am",											"おねえさん",			"oneesan"],
	["音楽",				"music",																			"おんがく",			"ongaku"],
	["お兄さん",			"older brother; elder brother; young man; buddy",									"おにいさん",			"oniisan"],
	["女",				"woman; female sex",																"おんな",				"onna"],
	["女の子",			"girl; daughter; young women",														"おんなのこ",			"onnanoko"],
	["多い",				"many; numerous; a lot; large quantity; frequent",									"おおい",				"ooi"],
	["大きい",			"big; large; great; important",														"おおきい",			"ookii"],
	["大きな",			"big; large; great",																"おおきな",			"ookina"],
	["大勢",				"crowd of people; great number of people",											"おおぜい",			"oozei"],
	["降りる",			"to get off",																		"おりる",				"oriru"],
	["お酒",				"alcohol",																			"おさけ",				"osake"],
	["お皿",				"plate; dish",																		"おさら",				"osara"],
	["教える",			"to teach",																			"おしえる",			"oshieru"],
	["遅い",				"slow; time-consuming; late",														"おそい",				"osoi"],
	["押す",				"to push; to press",																"おす",				"osu"],
	["お手洗い",			"toilet; restroom; lavatory; bathroom",												"おてあらい",			"otearai"],
	["男",				"man; male",																		"おとこ",				"otoko"],
	["男の子",			"boy; male child; baby boy",														"おとこのこ",			"otokonoko"],
	["大人",				"adult",																			"おとな",				"otona"],
	["一昨日",			"day before yesterday",																"おととい",			"ototoi"],
	["一昨年",			"year before last",																	"おととし",			"ototoshi"],
	["お父さん",			"father; dad; papa; pa; pop; daddy",												"おとうさん",			"otousan"],
	["弟",				"younger brother",																	"おとうと",			"otouto"],
	["終る",				"to finish; to end",																"おわる",				"owaru"],
	["泳ぐ",				"to swim",																			"およぐ",				"oyogu"],
	["来月",				"next month",																		"らいげつ",			"raigetsu"],
	["来年",				"next year",																		"らいねん",			"rainen"],
	["来週",				"next week",																		"らいしゅう",			"raishuu"],
	["零",				"zero",																				"れい",				"rei"],
	["冷蔵庫",			"refrigerator",																		"れいぞうこ",			"reizouko"],
	["練習",				"practice; practicing",																"れんしゅう",			"renshuu"],
	["立派",				"splendid",																			"りっぱ",				"rippa"],
	["六",				"six; 6",																			"ろく",				"roku"],
	["廊下",				"corridor; hallway; passageway",													"ろうか",				"rouka"],
	["旅行",				"travel; trip; journey; excursion; tour",											"りょこう",				"ryokou"],
	["料理",				"cuisine",																			"りょうり",				"ryouri"],
	["両親",				"parents; both parents",															"りょうしん",			"ryoushin"],
	["留学生",			"overseas student; exchange student",												"りゅうがくせい",		"ryuugakusei"],
	["財布",				"purse; wallet",																	"さいふ",				"saifu"],
	["魚",				"fish",																				"さかな",				"sakana"],
	["先",				"previous; prior; first; earlier",													"さき",				"saki"],
	["咲く",				"to bloom",																			"さく",				"saku"],
	["作文",				"writing; composition",																"さくぶん",			"sakubun"],
	["寒い",				"cold",																				"さむい",				"samui"],
	["三",				"three; 3",																			"さん",				"san"],
	["散歩",				"walk; stroll",																		"さんぽ",				"sanpo"],
	["再来年",			"year after next",																	"さらいねん",			"sarainen"],
	["差す",				"to stretch out hands; to raise an umbrella",										"さす",				"sasu"],
	["砂糖",				"sugar",																			"さとう",				"satou"],
	["背",				"height; stature; back; spine",														"せ",				"se"],
	["背広",				"business suit",																	"せびろ",				"sebiro"],
	["生徒",				"pupil; student",																	"せいと",				"seito"],
	["石鹼",				"soap",																				"せっけん",			"sekken"],
	["狭い",				"narrow",																			"せまい",				"semai"],
	["千",				"1000; thousand",																	"せん",				"sen"],
	["先月",				"last month",																		"せんげつ",			"sengetsu"],
	["先生",				"teacher; instructor; master",														"せんせい",			"sensei"],
	["先週",				"last week",																		"せんしゅう",			"senshuu"],
	["洗濯",				"washing; laundry",																	"せんたく",			"sentaku"],
	["写真",				"photograph; photo",																"しゃしん",			"shashin"],
	["四",				"four; 4",																			"し",				"shi"],
	["七",				"seven; 7",																			"しち",				"shichi"],
	["仕事",				"work; job; business",																"しごと",				"shigoto"],
	["閉まる",			"to close; to be closed",															"しまる",				"shimaru"],
	["締める",			"to tie; to fasten; to tighten",													"しめる",				"shimeru"],
	["閉める",			"to close; to shut",																"しめる",				"shimeru"],
	["新聞",				"newspaper",																		"しんぶん",			"shinbun"],
	["死ぬ",				"to die",																			"しぬ",				"shinu"],
	["塩",				"salt",																				"しお",				"shio"],
	["白",				"white; innocence; innocent person",												"しろ",				"shiro"],
	["白い",				"white",																			"しろい",				"shiroi"],
	["知る",				"to know",																			"しる",				"shiru"],
	["下",				"below; down; under; bottom",														"した",				"shita"],
	["質問",				"question; inquiry",																"しつもん",			"shitsumon"],
	["静か",				"quiet",																			"しずか",				"shizuka"],
	["食堂",				"cafeteria; dining room",															"しょくどう",			"shokudou"],
	["醬油",				"soy sauce",																		"しょうゆ",			"shouyu"],
	["宿題",				"homework; assignment; pending issue",												"しゅくだい",			"shukudai"],
	["空",				"sky; the air",																		"そら",				"sora"],
	["外",				"outside; exterior;",																"そと",				"soto"],
	["掃除",				"to clean; to sweep",																"そうじ",				"souji"],
	["直ぐに",			"immediately; right away; instantly",												"すぐに",				"sugu ni"],
	["水曜日",			"Wednesday",																		"すいようび",			"suiyoubi"],
	["好き",				"like",																				"すき",				"suki"],
	["少し",				"a little (bit); small quantity; few; short distance",								"すこし",				"sukoshi"],
	["少ない",			"few; a little; scarce; insufficient; seldom",										"すくない",			"sukunai"],
	["住む",				"to live in; to reside; to inhabit; to dwell; to abide",							"すむ",				"sumu"],
	["吸う",				"to smoke; to suck",																"すう",				"suu"],
	["座る",				"to sit",																			"すわる",				"suwaru"],
	["涼しい",			"refreshing; cool",																	"すずしい",			"suzushii"],
	["食べ物",			"food",																				"たべもの",			"tabemono"],
	["食べる",			"to eat",																			"たべる",				"taberu"],
	["多分",				"perhaps; probably",																"たぶん",				"tabun"],
	["大変",				"very; greatly; terribly; serious; difficult",										"たいへん",			"taihen"],
	["大切",				"important; necessary; indispensable; beloved",										"たいせつ",			"taisetsu"],
	["大使館",			"embassy",																			"たいしかん",			"taishikan"],
	["高い",				"high; tall; expensive; above average",												"たかい",				"takai"],
	["沢山",				"many",																				"たくさん",			"takusan"],
	["卵",				"eggs; egg",																		"たまご",				"tamago"],
	["誕生日",			"birthday",																			"たんじょうび",			"tanjoubi"],
	["頼む",				"to ask",																			"たのむ",				"tanomu"],
	["楽しい",			"enjoyable; fun",																	"たのしい",			"tanoshii"],
	["縦",				"length; height",																	"たて",				"tate"],
	["建物",				"building",																			"たてもの",			"tatemono"],
	["立つ",				"to stand; to stand up",															"たつ",				"tatsu"],
	["手",				"hand; arm",																		"て",				"te"],
	["手紙",				"Letter (message)",																	"てがみ",				"tegami"],
	["天気",				"weather; the elements",															"てんき",				"tenki"],
	["戸",				"Japanese style door",																"と",				"to"],
	["飛ぶ",				"to fly; to hop",																	"とぶ",				"tobu"],
	["時計",				"watch; clock; timepiece",															"とけい",				"tokei"],
	["時",				"time; moment; occasion; chance",													"とき",				"toki"],
	["時々",				"sometimes; at times",																"ときどき",			"tokidoki"],
	["所",				"place",																			"ところ",				"tokoro"],
	["止まる",			"to stop; to come to a halt",														"とまる",				"tomaru"],
	["友達",				"friend; companion",																"ともだち",			"tomodachi"],
	["隣",				"next door to",																		"となり",				"tonari"],
	["遠い",				"far",																				"とおい",				"tooi"],
	["十日",				"tenth day of the month / 10 days",													"とおか",				"tooka"],
	["鳥",				"bird",																				"とり",				"tori"],
	["鶏肉",				"chicken meat",																		"とりにく",			"toriniku"],
	["撮る",				"to take a photo or record a film",													"とる",				"toru"],
	["取る",				"to take; to pick up; to harvest; to earn; to win; to choose",						"とる",				"toru"],
	["年",				"year; age",																		"とし",				"toshi"],
	["図書館",			"library",																			"としょかん",			"toshokan"],
	["次",				"next",																				"つぎ",				"tsugi"],
	["一日",				"first day of the month",															"ついたち",			"tsuitachi"],
	["疲れる",			"to get tired",																		"つかれる",			"tsukareru"],
	["使う",				"to use",																			"つかう",				"tsukau"],
	["着く",				"to arrive at",																		"つく",				"tsuku"],
	["机",				"desk",																				"つくえ",				"tsukue"],
	["作る",				"to make",																			"つくる",				"tsukuru"],
	["詰まらない",			"boring",																			"つまらない",			"tsumaranai"],
	["冷たい",			"cold to the touch",																"つめたい",			"tsumetai"],
	["勤める",			"to work for someone",																"つとめる",			"tsutomeru"],
	["強い",				"powerful",																			"つよい",				"tsuyoi"],
	["上",				"above; up; over; top; surface",													"うえ",				"ue"],
	["生まれる",			"to be born",																		"うまれる",			"umareru"],
	["海",				"sea",																				"うみ",				"umi"],
	["売る",				"to sell",																			"うる",				"uru"],
	["煩い",				"noisy; annoying",																	"うるさい",			"urusai"],
	["後ろ",				"back; behind; rear",																"うしろ",				"ushiro"],
	["薄い",				"thin; weak",																		"うすい",				"usui"],
	["歌",				"song",																				"うた",				"uta"],
	["歌う",				"to sing",																			"うたう",				"utau"],
	["上着",				"coat; tunic; jacket; outer garment",												"うわぎ",				"uwagi"],
	["若い",				"young",																			"わかい",				"wakai"],
	["分かる",			"to understand; to comprehend; to grasp; to see; to get; to follow",				"わかる",				"wakaru"],
	["悪い",				"bad; poor; undesirable",															"わるい",				"warui"],
	["忘れる",			"to forget",																		"わすれる",			"wasureru"],
	["渡る",				"to go across",																		"わたる",				"wataru"],
	["私",				"I; myself",																		"わたし",				"watashi"],
	["渡す",				"to hand over",																		"わたす",				"watasu"],
	["山",				"mountain; hill",																	"やま",				"yama"],
	["八百屋",			"greengrocer; fruit and vegetable shop; versatile",									"やおや",				"yaoya"],
	["野菜",				"vegetable",																		"やさい",				"yasai"],
	["易しい",			"easy; simple",																		"やさしい",			"yasashii"],
	["安い",				"cheap; inexpensive",																"やすい",				"yasui"],
	["休み",				"rest; vacation; holiday",															"やすみ",				"yasumi"],
	["休む",				"to be absent; to take a day off; to rest",											"やすむ",				"yasumu"],
	["八つ",				"eight: 8",																			"やっつ",				"yattsu"],
	["呼ぶ",				"to call out; to invite",															"よぶ",				"yobu"],
	["良い",				"good",																				"よい",				"いい",			"yoi",			"ii"],
	["四日",				"fourth day of the month / 4 days",													"よっか",				"yokka"],
	["横",				"beside; side; width",																"よこ",				"yoko"],
	["読む",				"to read; to guess; to predict; to read (someone's thoughts)",						"よむ",				"yomu"],
	["夜",				"evening; night",																	"よる",				"yoru"],
	["四つ",				"four; 4",																			"よつ",				"yotsu"],
	["洋服",				"western clothes",																	"ようふく",			"youfuku"],
	["八日",				"eighth day of the month / 8 days",													"ようか",				"youka"],
	["弱い",				"weak",																				"よわい",				"yowai"],
	["雪",				"snow",																				"ゆき",				"yuki"],
	["昨夜",				"last night",																		"ゆうべ",				"yuube"],
	["郵便局",			"post office",																		"ゆうびんきょく",		"yuubinkyoku"],
	["夕方",				"evening; dusk",																	"ゆうがた",			"yuugata"],
	["夕飯",				"evening meal",																		"ゆうはん",			"yuuhan"],
	["有名",				"famous",																			"ゆうめい",			"yuumei"],
	["雑誌",				"magazine",																			"ざっし",				"zasshi"],
	["全部",				"all",																				"ぜんぶ",				"zenbu"],
]

// =======================================================================================================================================================================

const n4vocab = [
	["上がる",			"to rise",																			"あがる",				"agaru"],
	["挨拶",				"to greet",																			"あいさつ",			"aisatsu"],
	["味",				"flavor; taste; uniqueness; attractiveness; experience",							"あじ",				"aji"],
	["赤ちゃん",			"baby; infant",																		"あかちゃん",			"akachan"],
	["赤ん坊",			"baby; infant",																		"あかんぼう",			"akanbou"],
	["案内",				"to guide",																			"あんない",			"annai"],
	["安心",				"peace of mind",																	"あんしん",			"anshin"],
	["安全",				"safety; security",																	"あんぜん",			"anzen"],
	["浅い",				"shallow",																			"あさい",				"asai"],
	["遊び",				"playing",																			"あそび",				"asobi"],
	["集まる",			"to gather; to collect; to assemble",												"あつまる",			"atsumaru"],
	["集める",			"to collect; to assemble; to gather",												"あつめる",			"atsumeru"],
	["謝る",				"to apologize",																		"あやまる",			"ayamaru"],
	["倍",				"double",																			"ばい",				"bai"],
	["番組",				"program (e.g. TV)",																"ばんぐみ",			"bangumi"],
	["場所",				"place",																			"ばしょ",				"basho"],
	["美術館",			"art gallery; art museum",															"びじゅつかん",			"bijutsukan"],
	["僕",				"I (used by males)",																"ぼく",				"boku"],
	["貿易",				"trade",																			"ぼうえき",			"boueki"],
	["部長",				"manager; head (chief, director) of a section or department",						"ぶちょう",			"buchou"],
	["文学",				"literature",																		"ぶんがく",			"bungaku"],
	["文化",				"culture",																			"ぶんか",				"bunka"],
	["文法",				"grammar",																			"ぶんぽう",			"bunpou"],
	["血",				"blood",																			"ち",				"chi"],
	["力",				"energy; force; strength; might; power",											"ちから",				"chikara"],
	["地理",				"geography",																		"ちり",				"chiri"],
	["中学校",			"junior high school; middle school",												"ちゅうがっこう",			"chuugakkou"],
	["注意",				"caution",																			"ちゅうい",			"chuui"],
	["注射",				"injection",																		"ちゅうしゃ",			"chuusha"],
	["駐車場",			"parking lot",																		"ちゅうしゃじょう",		"chuushajou"],
	["大分",				"considerably; greatly; a lot",														"だいぶ",				"daibu"],
	["大学生",			"university student; college student",												"だいがくせい",			"daigakusei"],
	["大事",				"important; serious; crucial",														"だいじ",				"daiji"],
	["大体",				"roughly",																			"だいたい",			"daitai"],
	["暖房",				"heating",																			"だんぼう",			"danbou"],
	["男性",				"man; male",																		"だんせい",			"dansei"],
	["電報",				"telegram",																			"でんぽう",			"denpou"],
	["電灯",				"electric light",																	"でんとう",			"dentou"],
	["泥棒",				"thief",																			"どろぼう",			"dorobou"],
	["動物園",			"zoo; zoological gardens",															"どうぶつえん",			"doubutsuen"],
	["道具",				"tool",																				"どうぐ",				"dougu"],
	["枝",				"branch",																			"えだ",				"eda"],
	["遠慮",				"reserve; refraining",																"えんりょ",			"enryo"],
	["選ぶ",				"to choose",																		"えらぶ",				"erabu"],
	["不便",				"inconvenience",																	"ふべん",				"fuben"],
	["増える",			"to increase",																		"ふえる",				"fueru"],
	["深い",				"deep",																				"ふかい",				"fukai"],
	["復習",				"review (of learned material); revision",											"ふくしゅう",			"fukushuu"],
	["複雑",				"complexity; complication",															"ふくざつ",			"fukuzatsu"],
	["踏む",				"to step on",																		"ふむ",				"fumu"],
	["舟",				"ship",																				"ふね",				"fune"],
	["降り出す",			"to start to rain",																	"ふりだす",			"furidasu"],
	["布団",				"Japanese bedding; futon",															"ふとん",				"futon"],
	["太る",				"to become fat",																	"ふとる",				"futoru"],
	["普通",				"usually",																			"ふつう",				"futsuu"],
	["原因",				"cause",																			"げんいん",			"genin"],
	["下宿",				"lodging",																			"げしゅく",			"geshuku"],
	["技術",				"art, technology, skill",															"ぎじゅつ",			"gijutsu"],
	["ご覧になる",			"(respectful) to see",																"ごらんになる",			"goran ni naru"],
	["ご主人",			"your husband; her husband",														"ごしゅじん",			"goshujin"],
	["ご存じ",			"knowing",																			"ごぞんじ",			"gozonji"],
	["具合",				"condition; health",																"ぐあい",				"guai"],
	["葉",				"leaves; leaf",																		"は",				"ha"],
	["拝見",				"seeing; looking at",																"はいけん",			"haiken"],
	["歯医者",			"dentist",																			"はいしゃ",			"haisha"],
	["運ぶ",				"to carry",																			"はこぶ",				"hakobu"],
	["花見",				"cherry blossom viewing; flower viewing",											"はなみ",				"hanami"],
	["反対",				"opposition",																		"はんたい",			"hantai"],
	["払う",				"to pay",																			"はらう",				"harau"],
	["発音",				"pronunciation",																	"はつおん",			"hatsuon"],
	["林",				"woods; forest",																	"はやし",				"hayashi"],
	["恥ずかしい",			"embarrassed",																		"はずかしい",			"hazukashii"],
	["変",				"strange; peculiar; weird",															"へん",				"hen"],
	["返事",				"reply; answer; response",															"へんじ",				"henji"],
	["火",				"fire",																				"ひ",				"hi"],
	["酷い",				"terrible; awful",																	"ひどい",				"hidoi"],
	["冷える",			"to grow cold",																		"ひえる",				"hieru"],
	["髭",				"beard",																			"ひげ",				"hige"],
	["非常に",			"extremely",																		"ひじょうに",			"hijou ni"],
	["光",				"light",																			"ひかり",				"hikari"],
	["光る",				"to shine",																			"ひかる",				"hikaru"],
	["引き出し",			"drawer",																			"ひきだし",			"hikidashi"],
	["引き出す",			"to withdraw",																		"ひきだす",			"hikidasu"],
	["引っ越す",			"to move house",																	"ひっこす",			"hikkosu"],
	["飛行場",			"airfield; airport",																"ひこうじょう",			"hikoujou"],
	["開く",				"to open; to undo; to unseal; to unpack",											"ひらく",				"hiraku"],
	["拾う",				"to pick up",																		"ひろう",				"hirou"],
	["昼間",				"daytime; during the day",															"ひるま",				"hiruma"],
	["昼休み",			"lunch break; noon recess; noon rest period",										"ひるやすみ",			"hiruyasumi"],
	["久しぶり",			"after a long time",																"ひさしぶり",			"hisashiburi"],
	["褒める",			"to praise",																		"ほめる",				"homeru"],
	["翻訳",				"translation",																		"ほんやく",			"honyaku"],
	["星",				"star",																				"ほし",				"hoshi"],
	["法律",				"law",																				"ほうりつ",			"houritsu"],
	["放送",				"to broadcast",																		"ほうそう",			"housou"],
	["一度",				"once; one time; on one occasion",													"いちど",				"ichido"],
	["以外",				"with the exception of; excepting",													"いがい",				"igai"],
	["医学",				"medical science; medicine",														"いがく",				"igaku"],
	["以上",				"... and more; ... and upwards",													"いじょう",			"ijou"],
	["以下",				"not exceeding",																	"いか",				"ika"],
	["意見",				"opinion; view; comment",															"いけん",				"iken"],
	["生き物",			"living thing",																		"いきもの",			"ikimono"],
	["生きる",			"to live",																			"いきる",				"ikiru"],
	["以内",				"within",																			"いない",				"inai"],
	["田舎",				"countryside",																		"いなか",				"inaka"],
	["祈る",				"to pray",																			"いのる",				"inoru"],
	["色んな",			"various",																			"いろんな",			"ironna"],
	["石",				"stone",																			"いし",				"ishi"],
	["急ぐ",				"to hurry; to rush; to hasten; to make something happen sooner",					"いそぐ",				"isogu"],
	["一生懸命",			"very hard; with utmost effort",													"いっしょうけんめい",		"isshoukenmei"],
	["頂く",				"(humble) to receive",																"いただく",			"itadaku"],
	["致す",				"(humble) to do",																	"いたす",				"itasu"],
	["糸",				"thread",																			"いと",				"ito"],
	["字",				"character",																		"じ",				"ji"],
	["時代",				"period",																			"じだい",				"jidai"],
	["事故",				"accident",																			"じこ",				"jiko"],
	["事務所",			"office",																			"じむしょ",			"jimusho"],
	["神社",				"Shinto shrine",																	"じんじゃ",			"jinja"],
	["人口",				"population",																		"じんこう",			"jinkou"],
	["人生",				"human life",																		"じんせい",			"jinsei"],
	["地震",				"earthquake",																		"じしん",				"jishin"],
	["辞典",				"dictionary",																		"じてん",				"jiten"],
	["自由",				"freedom",																			"じゆう",				"jiyuu"],
	["女性",				"woman; female",																	"じょせい",			"josei"],
	["準備",				"to prepare",																		"じゅんび",			"junbi"],
	["十分",				"enough; sufficient; plenty; adequate; satisfactory",								"じゅうぶん",			"juubun"],
	["柔道",				"judo",																				"じゅうどう",			"juudou"],
	["住所",				"address",																			"じゅうしょ",			"juusho"],
	["壁",				"wall",																				"かべ",				"kabe"],
	["課長",				"section manager; section chief",													"かちょう",			"kachou"],
	["帰り",				"return; coming back",																"かえり",				"kaeri"],
	["変える",			"to change; to transform",															"かえる",				"kaeru"],
	["科学",				"science",																			"かがく",				"kagaku"],
	["鏡",				"mirror",																			"かがみ",				"kagami"],
	["海岸",				"coast",																			"かいがん",			"kaigan"],
	["会議",				"meeting; conference; session; assembly",											"かいぎ",				"kaigi"],
	["会議室",			"conference room; conference hall; council room",									"かいぎしつ",			"kaigishitsu"],
	["会場",				"assembly hall; meeting place; venue; grounds",										"かいじょう",			"kaijou"],
	["会話",				"conversation",																		"かいわ",				"kaiwa"],
	["火事",				"fire",																				"かじ",				"kaji"],
	["格好",				"appearance",																		"かっこう",			"kakkou"],
	["構う",				"to mind",																			"かまう",				"kamau"],
	["髪",				"hair",																				"かみ",				"kami"],
	["噛む",				"to bite, to chew",																	"かむ",				"kamu"],
	["家内",				"(my) wife; inside the home; one's family",											"かない",				"kanai"],
	["必ず",				"always; certainly",																"かならず",			"kanarazu"],
	["悲しい",			"sad",																				"かなしい",			"kanashii"],
	["考える",			"to think",																			"かんがえる",			"kangaeru"],
	["看護婦",			"female nurse",																		"かんごふ",			"kangofu"],
	["関係",				"relationship",																		"かんけい",			"kankei"],
	["彼女",				"she; her",																			"かのじょ",			"kanojo"],
	["簡単",				"simple; easy",																		"かんたん",			"kantan"],
	["彼",				"he; him; his",																		"かれ",				"kare"],
	["彼ら",				"they; them",																		"かれら",				"karera"],
	["形",				"shape",																			"かたち",				"katachi"],
	["片付ける",			"to tidy up",																		"かたづける",			"katadzukeru"],
	["硬い",				"hard",																				"かたい",				"katai"],
	["勝つ",				"to win",																			"かつ",				"katsu"],
	["乾く",				"to get dry",																		"かわく",				"kawaku"],
	["代わり",			"instead; in place",																"かわり",				"kawari"],
	["変わる",			"to change",																		"かわる",				"kawaru"],
	["通う",				"to commute",																		"かよう",				"kayou"],
	["飾る",				"to decorate",																		"かざる",				"kazaru"],
	["毛",				"hair or fur",																		"け",				"ke"],
	["怪我",				"to injure",																		"けが",				"kega"],
	["計画",				"to plan",																			"けいかく",			"keikaku"],
	["経験",				"to experience",																	"けいけん",			"keiken"],
	["警察",				"police",																			"けいさつ",			"keisatsu"],
	["経済",				"finance; economy",																	"けいざい",			"keizai"],
	["見物",				"sightseeing; visit",																"けんぶつ",			"kenbutsu"],
	["喧嘩",				"to quarrel",																		"けんか",				"kenka"],
	["研究",				"research",																			"けんきゅう",			"kenkyuu"],
	["研究室",			"laboratory",																		"けんきゅうしつ",		"kenkyuushitsu"],
	["景色",				"scenery",																			"けしき",				"keshiki"],
	["気",				"spirit",																			"き",				"ki"],
	["厳しい",			"strict",																			"きびしい",			"kibishii"],
	["気分",				"feeling; mood",																	"きぶん",				"kibun"],
	["機会",				"chance; opportunity",																"きかい",				"kikai"],
	["危険",				"danger",																			"きけん",				"kiken"],
	["聞こえる",			"to be heard; to be audible; to be said",											"きこえる",			"kikoeru"],
	["決まる",			"to be decided",																	"きまる",				"kimaru"],
	["決める",			"to decide",																		"きめる",				"kimeru"],
	["君",				"You",																				"きみ",				"kimi"],
	["気持ち",			"feeling",																			"きもち",				"kimochi"],
	["着物",				"kimono; Japanese traditional clothing",											"きもの",				"kimono"],
	["近所",				"neighbourhood",																	"きんじょ",			"kinjo"],
	["絹",				"silk",																				"きぬ",				"kinu"],
	["季節",				"season",																			"きせつ",				"kisetsu"],
	["汽車",				"train",																			"きしゃ",				"kisha"],
	["規則",				"rule",																				"きそく",				"kisoku"],
	["子",				"child",																			"こ",				"ko"],
	["心",				"heart",																			"こころ",				"kokoro"],
	["国際",				"international",																	"こくさい",				"kokusai"],
	["細かい",			"small,						 fine",													"こまかい",			"komakai"],
	["米",				"(husked grains of) rice",															"こめ",				"kome"],
	["込む",				"to be crowded",																	"こむ",				"komu"],
	["今度",				"this time; next time",																"こんど",				"kondo"],
	["この間",			"the other day; recently",															"このあいだ",			"konoaida"],
	["今夜",				"this evening; tonigh",																"こんや",				"konya"],
	["故障",				"to break-down",																	"こしょう",				"koshou"],
	["答え",				"response",																			"こたえ",				"kotae"],
	["小鳥",				"small bird",																		"ことり",				"kotori"],
	["校長",				"principal; headmaster",															"こうちょう",			"kouchou"],
	["講堂",				"auditorium",																		"こうどう",				"koudou"],
	["郊外",				"suburb; residential area on the outskirt of a city",								"こうがい",			"kougai"],
	["講義",				"lecture",																			"こうぎ",				"kougi"],
	["工業",				"industry",																			"こうぎょう",			"kougyou"],
	["工場",				"factory",																			"こうじょう",			"koujou"],
	["高校",				"senior high school; high school",													"こうこう",				"koukou"],
	["高校生",			"high school student",																"こうこうせい",			"koukousei"],
	["公務員",			"government worker",																"こうむいん",			"koumuin"],
	["高等学校",			"high school",																		"こうとうがっこう",		"koutougakkou"],
	["交通",				"traffic",																			"こうつう",			"koutsuu"],
	["怖い",				"frightening",																		"こわい",				"kowai"],
	["壊れる",			"to be broken",																		"こわれる",			"kowareru"],
	["壊す",				"to break",																			"こわす",				"kowasu"],
	["首",				"neck",																				"くび",				"kubi"],
	["下さる",			"(respectful) to give",																"くださる",			"kudasaru"],
	["雲",				"cloud",																			"くも",				"kumo"],
	["君",				"suffix for familiar young male",													"くん",				"kun"],
	["比べる",			"to compare",																		"くらべる",			"kuraberu"],
	["暮れる",			"to get dark",																		"くれる",				"kureru"],
	["草",				"grass",																			"くさ",				"kusa"],
	["空気",				"air",																				"くうき",				"kuuki"],
	["空港",				"airport",																			"くうこう",				"kuukou"],
	["客",				"guest; customer",																	"きゃく",				"kyaku"],
	["教育",				"education",																		"きょういく",			"kyouiku"],
	["教会",				"church; congregation; Christian church",											"きょうかい",			"kyoukai"],
	["興味",				"interest (in something); curiosity (about something); zest (for)",					"きょうみ",			"kyoumi"],
	["競争",				"competition",																		"きょうそう",			"kyousou"],
	["急",				"sudden; abrupt; unexpected",														"きゅう",				"kyuu"],
	["急行",				"hurrying (to somewhere); rushing; hastening",										"きゅうこう",			"kyuukou"],
	["間違える",			"to make a mistake (in)",															"まちがえる",			"machigaeru"],
	["参る",				"(humble) to go; to come",															"まいる",				"mairu"],
	["負ける",			"to lose",																			"まける",				"makeru"],
	["漫画",				"comic",																			"まんが",				"manga"],
	["間に合う",			"to be in time (for)",																"まにあう",			"maniau"],
	["真ん中",			"middle; centre; center",															"まんなか",			"mannaka"],
	["周り",				"around",																			"まわり",				"mawari"],
	["回る",				"to go around",																		"まわる",				"mawaru"],
	["召し上がる",			"to eat; to drink",																	"めしあがる",			"meshiagaru"],
	["珍しい",			"unusual; rare",																	"めずらしい",			"mezurashii"],
	["見える",			"to be seen; to be in sight; to look; to seem",										"みえる",				"mieru"],
	["港",				"harbour",																			"みなと",				"minato"],
	["味噌",				"fermented condiment made from soybeans",											"みそ",				"miso"],
	["見つかる",			"to be found; to be discovered",													"みつかる",			"mitsukaru"],
	["見つける",			"to discover; to find; to come across; to detect; to spot",							"みつける",			"mitsukeru"],
	["都",				"capital",																			"みやこ",				"miyako"],
	["湖",				"lake",																				"みずうみ",			"mizuumi"],
	["戻る",				"to turn back",																		"もどる",				"modoru"],
	["木綿",				"cotton (material)",																"もめん",				"momen"],
	["森",				"forest",																			"もり",				"mori"],
	["申し上げる",			"to say; to offer",																	"もうしあげる",			"moushiageru"],
	["申す",				"to be called; to say",																"もうす",				"mousu"],
	["迎える",			"to go out to meet",																"むかえる",			"mukaeru"],
	["昔",				"olden days; former",																"むかし",				"mukashi"],
	["向かう",			"to head towards",																	"むかう",				"mukau"],
	["無理",				"impossible",																		"むり",				"muri"],
	["虫",				"insect",																			"むし",				"mushi"],
	["息子",				"son",																				"むすこ",				"musuko"],
	["娘",				"daughter",																			"むすめ",				"musume"],
	["投げる",			"to throw or cast away",															"なげる",				"nageru"],
	["泣く",				"to weep",																			"なく",				"naku"],
	["無くなる",			"to disappear; to get lost",														"なくなる",			"naku naru"],
	["亡くなる",			"to die",																			"なくなる",			"nakunaru"],
	["生",				"raw",																				"なま",				"nama"],
	["直る",				"to be fixed; to be repaired",														"なおる",				"naoru"],
	["治る",				"to be cured; to heal",																"なおる",				"naoru"],
	["慣れる",			"to get used to",																	"なれる",				"nareru"],
	["鳴る",				"to sound",																			"なる",				"naru"],
	["寝坊",				"sleeping in late; oversleeping",													"ねぼう",				"nebou"],
	["値段",				"price; cost",																		"ねだん",				"nedan"],
	["眠い",				"sleepy",																			"ねむい",				"nemui"],
	["眠る",				"to sleep",																			"ねむる",				"nemuru"],
	["熱",				"fever",																			"ねつ",				"netsu"],
	["苦い",				"bitter",																			"にがい",				"nigai"],
	["逃げる",			"to escape",																		"にげる",				"nigeru"],
	["二階建て",			"two-storied building",																"にかいだて",			"nikaidate"],
	["人形",				"doll",																				"にんぎょう",			"ningyou"],
	["匂い",				"a smell",																			"におい",				"nioi"],
	["似る",				"to be similar",																	"にる",				"niru"],
	["喉",				"throat",																			"のど",				"nodo"],
	["残る",				"to remain",																		"のこる",				"nokoru"],
	["乗り換える",			"to change between buses or trains",												"のりかえる",			"norikaeru"],
	["乗り物",			"vehicle",																			"のりもの",			"norimono"],
	["濡れる",			"to get wet",																		"ぬれる",				"nureru"],
	["塗る",				"to paint; to plaster",																"ぬる",				"nuru"],
	["盗む",				"to steal",																			"ぬすむ",				"nusumu"],
	["入学",				"entry to school or university; enrollment",										"にゅうがく",			"nyuugaku"],
	["入院",				"hospitalization",																	"にゅういん",			"nyuuin"],
	["落ちる",			"to fall or drop",																	"おちる",				"ochiru"],
	["踊り",				"a dance",																			"おどり",				"odori"],
	["驚く",				"to be surprised",																	"おどろく",			"odoroku"],
	["踊る",				"to dance",																			"おどる",				"odoru"],
	["お出でになる",		"(respectful) to be",																"おいでになる",			"oide ni naru"],
	["お祝い",			"congratulation",																	"おいわい",			"oiwai"],
	["お嬢さん",			"(another's) daughter",																"おじょうさん",			"ojousan"],
	["可笑しい",			"strange or funny",																	"おかしい",			"okashii"],
	["行う",				"to perform; to do; to carry out",													"おこなう",			"okonau"],
	["怒る",				"to be angry",																		"おこる",				"okoru"],
	["起こす",			"to wake",																			"おこす",				"okosu"],
	["億",				"one hundred million",																"おく",				"oku"],
	["屋上",				"rooftop",																			"おくじょう",			"okujou"],
	["遅れる",			"to be late",																		"おくれる",			"okureru"],
	["贈り物",			"present; gift",																	"おくりもの",			"okurimono"],
	["送る",				"to send",																			"おくる",				"okuru"],
	["お祭り",			"festival",																			"おまつり",			"omatsuri"],
	["お見舞い",			"visiting ill or distressed people",												"おみまい",			"omimai"],
	["お土産",			"souvenir",																			"おみやげ",			"omiyage"],
	["思い出す",			"to remember",																		"おもいだす",			"omoidasu"],
	["表",				"the front",																		"おもて",				"omote"],
	["お礼",				"thanks",																			"おれい",				"orei"],
	["折れる",			"to break; to be broken",															"おれる",				"oreru"],
	["下りる",			"to get off",																		"おりる",				"oriru"],
	["折る",				"to break or to fold",																"おる",				"oru"],
	["押し入れ",			"closet",																			"おしいれ",			"oshiire"],
	["仰る",				"(respectful) to say",																"おっしゃる",			"ossharu"],
	["お宅",				"your home",																		"おたく",				"otaku"],
	["音",				"sound; note",																		"おと",				"oto"],
	["落とす",			"to drop",																			"おとす",				"otosu"],
	["お釣り",			"change (for a purchase)",															"おつり",				"otsuri"],
	["夫",				"husband",																			"おっと",				"otto"],
	["終わり",			"the end",																			"おわり",				"owari"],
	["親",				"parents",																			"おや",				"oya"],
	["泳ぎ方",			"way of swimming",																	"およぎかた",			"oyogikata"],
	["冷房",				"air conditioning",																	"れいぼう",			"reibou"],
	["歴史",				"history",																			"れきし",				"rekishi"],
	["連絡",				"to contact; to get in touch",														"れんらく",			"renraku"],
	["利用",				"use; utilization; application",													"りよう",				"riyou"],
	["理由",				"reason",																			"りゆう",				"riyuu"],
	["留守",				"absence",																			"るす",				"rusu"],
	["旅館",				"traditional inn; Japanese-style lodging",											"りょかん",			"ryokan"],
	["両方",				"both sides",																		"りょうほう",			"ryouhou"],
	["寂しい",			"lonely",																			"さびしい",			"sabishii"],
	["下がる",			"to get down",																		"さがる",				"sagaru"],
	["探す",				"to look for",																		"さがす",				"sagasu"],
	["下げる",			"to lower",																			"さげる",				"sageru"],
	["最後",				"end; last",																		"さいご",				"saigo"],
	["最近",				"recently",																			"さいきん",			"saikin"],
	["最初",				"beginning; first",																	"さいしょ",			"saisho"],
	["坂",				"slope; hill",																		"さか",				"saka"],
	["盛ん",				"popularity; prosperous",															"さかん",				"sakan"],
	["昨夜",				"last night",																		"さくや",				"sakuya"],
	["産業",				"industry",																			"さんぎょう",			"sangyou"],
	["再来月",			"month after next",																	"さらいげつ",			"saraigetsu"],
	["再来週",			"week after next",																	"さらいしゅう",			"saraishuu"],
	["差し上げる",			"to give",																			"さしあげる",			"sashiageru"],
	["騒ぐ",				"to make noise; to be excited",														"さわぐ",				"sawagu"],
	["触る",				"to touch",																			"さわる",				"sawaru"],
	["生物",				"living thing",																		"せいぶつ",			"seibutsu"],
	["政治",				"politics",																			"せいじ",				"seiji"],
	["生活",				"to live",																			"せいかつ",			"seikatsu"],
	["生命",				"life",																				"せいめい",			"seimei"],
	["生産",				"production",																		"せいさん",			"seisan"],
	["西洋",				"the west; Western countries",														"せいよう",			"seiyou"],
	["世界",				"the world",																		"せかい",				"sekai"],
	["席",				"seat",																				"せき",				"seki"],
	["線",				"line",																				"せん",				"sen"],
	["背中",				"back (of body)",																	"せなか",				"senaka"],
	["先輩",				"senior",																			"せんぱい",			"senpai"],
	["戦争",				"war",																				"せんそう",			"sensou"],
	["説明",				"explanation",																		"せつめい",			"setsumei"],
	["社長",				"company president; manager; director",												"しゃちょう",			"shachou"],
	["社会",				"society; public; community; the world",											"しゃかい",			"shakai"],
	["市",				"city",																				"し",				"shi"],
	["試合",				"match; game",																		"しあい",				"shiai"],
	["叱る",				"to scold",																			"しかる",				"shikaru"],
	["仕方",				"way; method",																		"しかた",				"shikata"],
	["試験",				"examination",																		"しけん",				"shiken"],
	["島",				"island",																			"しま",				"shima"],
	["市民",				"citizen",																			"市民",				"shimin"],
	["品物",				"goods; article; thing",															"しなもの",			"shinamono"],
	["新聞社",			"newspaper company",																"しんぶんしゃ",			"shinbunsha"],
	["親切",				"kindness",																			"しんせつ",			"shinsetsu"],
	["失敗",				"failure",																			"しっぱい",			"shippai"],
	["調べる",			"to investigate",																	"しらべる",			"shiraberu"],
	["知らせる",			"to notify",																		"しらせる",			"shiraseru"],
	["下着",				"underwear",																		"したぎ",				"shitagi"],
	["食料品",			"food; groceries",																	"しょくりょうひん",		"shokuryouhin"],
	["小学校",			"elementary school",																"しょうがっこう",			"shougakkou"],
	["生じる",			"to produce",																		"しょうじる",			"shoujiru"],
	["紹介",				"introduction",																		"しょうかい",			"shoukai"],
	["将来",				"future",																			"しょうらい",			"shourai"],
	["小説",				"novel",																			"しょうせつ",			"shousetsu"],
	["趣味",				"hobby; pastime; preference",														"しゅみ",				"shumi"],
	["習慣",				"habit; custom; cultural practice.",												"しゅうかん",			"shuukan"],
	["祖母",				"grandmother",																		"そぼ",				"sobo"],
	["育てる",			"to rear; to bring up",																"そだてる",			"sodateru"],
	["祖父",				"grandfather",																		"そふ",				"sofu"],
	["卒業",				"graduation",																		"そつぎょう",			"sotsugyou"],
	["相談",				"to discuss",																		"そうだん",			"soudan"],
	["素晴らしい",			"wonderful",																		"すばらしい",			"subarashii"],
	["滑る",				"to slide; to slip",																"すべる",				"suberu"],
	["凄い",				"terrific",																			"すごい",				"sugoi"],
	["水道",				"water supply",																		"すいどう",			"suidou"],
	["水泳",				"swimming",																			"すいえい",			"suiei"],
	["空く",				"to be hungry",																		"すく",				"suku"],
	["隅",				"corner; nook",																		"すみ",				"sumi"],
	["済む",				"to finish",																		"すむ",				"sumu"],
	["砂",				"sand",																				"すな",				"suna"],
	["進む",				"to make progress",																	"すすむ",				"susumu"],
	["捨てる",			"to throw away",																	"すてる",				"suteru"],
	["数学",				"mathematics; arithmetic",															"すうがく",			"suugaku"],
	["正しい",			"right; correct",																	"ただしい",			"tadashii"],
	["退院",				"leaving hospital; discharge from hospital",										"たいいん",			"taiin"],
	["台風",				"typhoon",																			"たいふう",			"taifuu"],
	["棚",				"shelves",																			"たな",				"tana"],
	["誕生",				"birth",																			"たんじょう",			"tanjou"],
	["楽しみ",			"looking forward to",																"たのしみ",			"tanoshimi"],
	["倒れる",			"to fall (over,	down)",																"たおれる",			"taoreru"],
	["足りる",			"to be sufficient; to be enough",													"たりる",				"tariru"],
	["足す",				"to add (numbers / something)",														"たす",				"tasu"],
	["畳",				"Japanese straw mat",																"たたみ",				"tatami"],
	["建てる",			"to build",																			"たてる",				"tateru"],
	["訪ねる",			"to visit",																			"たずねる",			"tazuneru"],
	["尋ねる",			"to ask",																			"たずねる",			"tazuneru"],
	["手袋",				"glove",																			"てぶくろ",			"tebukuro"],
	["丁寧",				"polite",																			"ていねい",			"teinei"],
	["適当",				"suitable",																			"てきとう",			"tekitou"],
	["点",				"point; dot",																		"てん",				"ten"],
	["店員",				"employee (of a store); shop assistant; clerk",										"てんいん",			"tenin"],
	["天気予報",			"weather forecast",																	"てんきよほう",			"tenkiyohou"],
	["展覧会",			"exhibition",																		"てんらんかい",			"tenrankai"],
	["寺",				"temple",																			"てら",				"tera"],
	["手伝う",			"to help; to assist; to aid",														"てつだう",			"tetsudau"],
	["途中",				"on the way",																		"とちゅう",			"tochuu"],
	["届ける",			"to send",																			"とどける",			"todokeru"],
	["特急",				"limited express (train, faster than an express)",									"とっきゅう",			"tokkyuu"],
	["床屋",				"barber",																			"とこや",				"tokoya"],
	["特別",				"special; particular; extraordinary; exceptional",									"とくべつ",			"tokubetsu"],
	["特に",				"particularly; especially; in particular; expressly",								"とくに",				"tokuni"],
	["泊まる",			"to stay at",																		"とまる",				"tomaru"],
	["止める",			"to stop something",																"とめる",				"tomeru"],
	["遠く",				"distant",																			"とおく",				"tooku"],
	["通る",				"to go through",																	"とおる",				"tooru"],
	["取り替える",			"to exchange; to swap; to replace",													"とりかえる",			"torikaeru"],
	["到頭",				"finally,						 after all",										"とうとう",			"toutou"],
	["続ける",			"to continue; to keep up; to keep on",												"つづける",			"tsudzukeru"],
	["続く",				"to continue",																		"つづく",				"tsudzuku"],
	["都合",				"convenience",																		"つごう",				"tsugou"],
	["捕まえる",			"to catch",																			"つかまえる",			"tsukamaeru"],
	["漬ける",			"to soak; to pickle",																"つける",				"tsukeru"],
	["月",				"moon",																				"つき",				"tsuki"],
	["付く",				"to be attached",																	"つく",				"tsuku"],
	["妻",				"(humble) wife",																	"つま",				"tsuma"],
	["連れる",			"to take (someone) with one",														"つれる",				"tsureru"],
	["釣る",				"to fish",																			"つる",				"tsuru"],
	["伝える",			"to report; to tell",																"つたえる",			"tsutaeru"],
	["包む",				"to wrap",																			"つつむ",				"tsutsumu"],
	["腕",				"arm",																				"うで",				"ude"],
	["植える",			"to plant; to grow",																"うえる",				"ueru"],
	["動く",				"to move",																			"うごく",				"ugoku"],
	["伺う",				"to visit",																			"うかがう",			"ukagau"],
	["受ける",			"to take a lesson or test",															"うける",				"ukeru"],
	["受付",				"reception (desk); information desk",												"うけつけ",			"uketsuke"],
	["生まれ",			"birth",																			"うまれ",				"umare"],
	["運転手",			"driver; chauffeur",																"うんてんしゅ",			"untenshu"],
	["裏",				"reverse side",																		"うら",				"ura"],
	["嬉しい",			"happy",																			"うれしい",			"ureshii"],
	["売り場",			"selling area",																		"うりば",				"uriba"],
	["嘘",				"a lie",																			"うそ",				"uso"],
	["打つ",				"to hit",																			"うつ",				"utsu"],
	["美しい",			"beautiful",																		"うつくしい",			"utsukushii"],
	["移る",				"to move house or transfer",														"うつる",				"utsuru"],
	["写す",				"to copy or photograph",															"うつす",				"utsusu"],
	["別れる",			"to separate",																		"わかれる",			"wakareru"],
	["沸かす",			"to boil; to heat",																	"わかす",				"wakasu"],
	["沸く",				"to boil",																			"わく",				"waku"],
	["笑う",				"to laugh; to smile",																"わらう",				"warau"],
	["割れる",			"to break",																			"われる",				"wareru"],
	["割合",				"rate; ratio",																		"わりあい",			"wariai"],
	["忘れ物",			"lost article",																		"わすれもの",			"wasuremono"],
	["焼ける",			"to burn; to be roasted",															"やける",				"yakeru"],
	["焼く",				"to bake; to grill",																"やく",				"yaku"],
	["役に立つ",			"to be helpful",																	"やくにたつ",			"yakunitatsu"],
	["約束",				"promise",																			"やくそく",			"yakusoku"],
	["止む",				"to stop",																			"やむ",				"yamu"],
	["優しい",			"kind",																				"やさしい",			"yasashii"],
	["痩せる",			"to become thin",																	"やせる",				"yaseru"],
	["柔らかい",			"soft",																				"やわらかい",			"yawarakai"],
	["汚れる",			"to get dirty",																		"よごれる",			"yogoreru"],
	["喜ぶ",				"to be delighted",																	"よろこぶ",			"yorokobu"],
	["寄る",				"to visit; to drop by",																"よる",				"yoru"],
	["予習",				"preparation for a lesson",															"よしゅう",			"yoshuu"],
	["予定",				"plan",																				"よてい",				"yotei"],
	["用",				"business; task; errand; use; purpose",												"よう",				"you"],
	["用意",				"preparation; arrangements; provision; getting ready",								"ようい",				"youi"],
	["用事",				"tasks; things to do; errand; business (to take care of)",							"ようじ",				"youji"],
	["予約",				"reservation",																		"よやく",				"yoyaku"],
	["湯",				"hot water",																		"ゆ",				"yu"],
	["指",				"finger",																			"ゆび",				"yubi"],
	["指輪",				"finger ring",																		"ゆびわ",				"yubiwa"],
	["夢",				"dream",																			"ゆめ",				"yume"],
	["揺れる",			"to shake",																			"ゆれる",				"yureru"],
	["残念",				"regrettable; unfortunate",															"ざんねん",			"zannen"],
	["全然",				"not entirely (used in a negative sentence)",										"ぜんぜん",			"zenzen"],
]
